// Placeholder generated-style file.
//
// This file is normally auto-generated by running:
//   flutterfire configure
// from inside /mobile, once you have a real Firebase project. That command
// overwrites this file with your project's real values for each platform.
//
// The values below are placeholders so the app compiles before you've
// connected a Firebase project; sign-in and Firestore calls will fail with a
// clear "invalid API key" style error until you run flutterfire configure.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` from /mobile.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id-web',
    messagingSenderId: '0',
    projectId: 'demo-project',
    authDomain: 'demo.firebaseapp.com',
    storageBucket: 'demo-project.appspot.com',
  );

  static const android = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id-android',
    messagingSenderId: '0',
    projectId: 'demo-project',
    storageBucket: 'demo-project.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: 'demo-app-id-ios',
    messagingSenderId: '0',
    projectId: 'demo-project',
    storageBucket: 'demo-project.appspot.com',
    iosBundleId: 'com.schooldemo.schoolPortal',
  );
}
